create table CLIENT_MASTER(CLIENTNO varchar(6)PRIMARY KEY,NAME VARCHAR(20)not null,ADDRESS1 VARCHAR(30),ADDRESS2 VARCHAR(30),
CITY VARCHAR(15),PINCODE INT,STATE VARCHAR(150),BALDUE NUMERIC) 
INSERT INTO CLIENT_MASTER (ClientNo,Name,CIty,Pincode,State,Baldue) VALUES('C0001','ivan Bayross','mumbai',40054,'Maharastra',15000);

create table PRODUCT_MASTER(PRODUCTNO VARCHAR(6) PRIMARY KEY,DESCRIPTION VARCHAR(15)NOT NULL,PROFITPERC NUMERIC NOT NULL,UNITMEASURE 
varchar(20)NOT NULL,QTYONHAND NUMERIC NOT NULL,REORDERLVL NUMERIC NOT NULL,SELLPRICE NUMERIC NOT NULL,COSTPRICE NUMERIC NOT NULL);
INSERT INTO product_Master values ('P00001','T-SHIRT',5,'Piece',200,50,350,250);

create table SALESMAN_MASTER(SALESMANNO VARCHAR(6)PRIMARY KEY,SALESMANNAME VARCHAR(20) NOT NULL,ADDRESS1 VARCHAR(20)NOT NULL,
ADDRESS2 VARCHAR(30),CITY VARCHAR(20),PINCODE NUMERIC,STATE VARCHAR(20),SALANT NUMERIC NOT NULL,SALAMT NUMERIC NOT NULL,TGTTOGET NUMERIC
NOT NULL,YTDSALES NUMERIC NOT NULL,REMARKS VARCHAR(60));
INSERT INTO Salesman_master VALUES('S0001','Aman','A/14','Woril','Mumbai','40002','Maharastra',3000,100,50,'Good');

create table SALES_ORDER(ORDERNO VARCHAR(6) PRIMARY KEY,CLIENTNO VARCHAR(6),ORDERDATE DATE,
DELYADDR VARCHAR(25),SALESMANNO VARCHAR(6),DELYTYPE  CHAR(1)  CHECK(DELYTYPE LIKE' %P%' OR DELYTYPE LIKE '%F%'),
BILLEDYN CHAR(1)CHECK(BILLEDYN LIKE '%Y%' OR BILLEDYN LIKE '%N%' ),DELYDATE DATE,
ORDERSTATUS VARCHAR(10) CHECK(ORDERSTATUS ='IN PROCESS' OR ORDERSTATUS ='Fulfilled' OR ORDERSTATUS ='Backorder' OR ORDERSTATUS = 'Cancelled'),
foreign key (CLIENTNO)REFERENCES Client_Master(CLIENTNO),foreign key (SALESMANNO)REFERENCES SALESMAN_MASTER(SALESMANNO));
INSERT INTO SALES_ORDER(ORDERNO,ORDERDATE,CLIENTNO,DELYTYPE,BILLEDYN,SALESMANNO,DELYDATE,ORDERSTATUS)
values('O19001','12-june-12','C00001','F','N','S00001','20-july-02','In process');
SELECT * FROM SALES_ORDER;

create table SALES_ORDER_DETAILS(ORDERNO VARCHAR(6),PRODUCTNO VARCHAR(6),QTYORDERED NUMERIC(8),
QTYDISP NUMERIC(8),PRODUCTRATE NUMERIC(10,2),FOREIGN KEY(ORDERNO)REFERENCES SALES_ORDER(ORDERNO),
FOREIGN KEY(PRODUCTNO)REFERENCES PRODUCT_MASTER(PRODUCTNO));
insert into SALES_ORDER_DETAILS(ORDERNO,PRODUCTNO,QTYORDERED,QTYDISP,PRODUCTRATE)values('O19001','P00001',4,4,525);

SELECT NAME FROM Client_Master;
SELECT NAME FROM Client_Master WHERE CITY='MUMBAI';
SELECT PRODUCTNO FROM PRODUCT_MASTER WHERE SELLPRICE BETWEEN 2000 AND 5000;
select NAME,CITY,STATE from Client_Master where STATE != 'MAHARASHTRA';
SELECT * FROM Client_Master WHERE CLIENTNO = 'C00001' OR CLIENTNO = 'C00002';
UPDATE Product_Master SET SELLPRICE='1150.50'where SELLPRICE='350';
DELETE FROM Client_Master WHERE CLIENTNO='C00002';
SELECT * FROM Client_Master WHERE CITY LIKE '_U%';
SELECT COUNT(*) AS NUMBER FROM Product_Master  WHERE SELLPRICE>=1500;

